// Generated by gencpp from file traxxas_node/AckermannDriveMsg.msg
// DO NOT EDIT!


#ifndef TRAXXAS_NODE_MESSAGE_ACKERMANNDRIVEMSG_H
#define TRAXXAS_NODE_MESSAGE_ACKERMANNDRIVEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traxxas_node
{
template <class ContainerAllocator>
struct AckermannDriveMsg_
{
  typedef AckermannDriveMsg_<ContainerAllocator> Type;

  AckermannDriveMsg_()
    : steering_angle(0.0)
    , steering_angle_velocity(0.0)
    , speed(0.0)
    , acceleration(0.0)
    , jerk(0.0)  {
    }
  AckermannDriveMsg_(const ContainerAllocator& _alloc)
    : steering_angle(0.0)
    , steering_angle_velocity(0.0)
    , speed(0.0)
    , acceleration(0.0)
    , jerk(0.0)  {
    }



   typedef float _steering_angle_type;
  _steering_angle_type steering_angle;

   typedef float _steering_angle_velocity_type;
  _steering_angle_velocity_type steering_angle_velocity;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef float _jerk_type;
  _jerk_type jerk;




  typedef boost::shared_ptr< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> const> ConstPtr;

}; // struct AckermannDriveMsg_

typedef ::traxxas_node::AckermannDriveMsg_<std::allocator<void> > AckermannDriveMsg;

typedef boost::shared_ptr< ::traxxas_node::AckermannDriveMsg > AckermannDriveMsgPtr;
typedef boost::shared_ptr< ::traxxas_node::AckermannDriveMsg const> AckermannDriveMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace traxxas_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'traxxas_node': ['/home/awesome/catkin_ws/src/traxxas_node/msg', '/home/awesome/catkin_ws/src/traxxas_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3512e91b48d69674a0e86fadf1ea8231";
  }

  static const char* value(const ::traxxas_node::AckermannDriveMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3512e91b48d69674ULL;
  static const uint64_t static_value2 = 0xa0e86fadf1ea8231ULL;
};

template<class ContainerAllocator>
struct DataType< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traxxas_node/AckermannDriveMsg";
  }

  static const char* value(const ::traxxas_node::AckermannDriveMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Average angle of the front wheels in radians (left is positive).\n\
# This angle is the true turning angle for bicycles and motorcycles. \n\
# It is an approximation for a car, computed by taking the average \n\
# of the angles of the 2 front wheels.\n\
float32 steering_angle\n\
\n\
# Desired rate of change of the steering angle in radians/second.\n\
float32 steering_angle_velocity\n\
\n\
# Speed of the center of the rear axle in meters/second (reverse is negative)\n\
float32 speed\n\
\n\
# Desired acceleration of the center of the rear axle in meters/second^2\n\
float32 acceleration\n\
\n\
# Desired jerk of the center of the rear axle in meters/second^3\n\
float32 jerk\n\
";
  }

  static const char* value(const ::traxxas_node::AckermannDriveMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering_angle);
      stream.next(m.steering_angle_velocity);
      stream.next(m.speed);
      stream.next(m.acceleration);
      stream.next(m.jerk);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AckermannDriveMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traxxas_node::AckermannDriveMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traxxas_node::AckermannDriveMsg_<ContainerAllocator>& v)
  {
    s << indent << "steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.steering_angle);
    s << indent << "steering_angle_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.steering_angle_velocity);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "jerk: ";
    Printer<float>::stream(s, indent + "  ", v.jerk);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAXXAS_NODE_MESSAGE_ACKERMANNDRIVEMSG_H
