// Generated by gencpp from file outdoor_navigation/NavFlagMsg.msg
// DO NOT EDIT!


#ifndef OUTDOOR_NAVIGATION_MESSAGE_NAVFLAGMSG_H
#define OUTDOOR_NAVIGATION_MESSAGE_NAVFLAGMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace outdoor_navigation
{
template <class ContainerAllocator>
struct NavFlagMsg_
{
  typedef NavFlagMsg_<ContainerAllocator> Type;

  NavFlagMsg_()
    : robot_id(0)  {
    }
  NavFlagMsg_(const ContainerAllocator& _alloc)
    : robot_id(0)  {
    }



   typedef uint32_t _robot_id_type;
  _robot_id_type robot_id;




  typedef boost::shared_ptr< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> const> ConstPtr;

}; // struct NavFlagMsg_

typedef ::outdoor_navigation::NavFlagMsg_<std::allocator<void> > NavFlagMsg;

typedef boost::shared_ptr< ::outdoor_navigation::NavFlagMsg > NavFlagMsgPtr;
typedef boost::shared_ptr< ::outdoor_navigation::NavFlagMsg const> NavFlagMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace outdoor_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'outdoor_navigation': ['/home/awesome/catkin_ws/src/outdoor_navigation/msg', '/home/awesome/catkin_ws/src/outdoor_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "643c2c9b3dd26758833f013bbe8b0a36";
  }

  static const char* value(const ::outdoor_navigation::NavFlagMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x643c2c9b3dd26758ULL;
  static const uint64_t static_value2 = 0x833f013bbe8b0a36ULL;
};

template<class ContainerAllocator>
struct DataType< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "outdoor_navigation/NavFlagMsg";
  }

  static const char* value(const ::outdoor_navigation::NavFlagMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32  robot_id\n\
";
  }

  static const char* value(const ::outdoor_navigation::NavFlagMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct NavFlagMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::outdoor_navigation::NavFlagMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::outdoor_navigation::NavFlagMsg_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OUTDOOR_NAVIGATION_MESSAGE_NAVFLAGMSG_H
