#!/usr/bin/expect -f

set user [lindex $argv 0]
set dest_ip [lindex $argv 1]
set dest_user [lindex $argv 2]
set dest_password [lindex $argv 3]

# connect via scp
spawn scp "/home/$user/ros_outdoor_navigation_data/waypoints.csv" "$dest_user@10.11.12.$dest_ip:~/ros_outdoor_navigation_data/waypoints.csv"
#######################
expect {
  -re ".*es.*o.*" {
    exp_send "yes\r"
    exp_continue
  }
  -re ".*sword.*" {
    exp_send "$dest_password\r"
  }
}
interact

